Repository hirofumi0810/neural_sp, pull requests merged in 2020-12, with the labels that each got.

#192 Fix snapshot saving
  neural_sp/trainers/lr_scheduler.py
Labels: bug, refactoring

#193 Fix subsampling rate calculation for auxiliary tasks
  neural_sp/bin/train_utils.py
Labels: bug

#195 Add GroupNorm option to Conformer block
  neural_sp/models/modules/conformer_convolution.py
  test/modules/test_conformer_convolution.py
Labels: enhancement

#196 Refactor phone MTL recipe
  examples/csj/s5/run.sh
  examples/csj/s5/run_2mtl.sh
  examples/librispeech/s5/run.sh
  examples/librispeech/s5/run_2mtl.sh
  examples/swbd/s5c/run.sh
  examples/swbd/s5c/run_2mtl.sh
  examples/swbd/s5c/run_3mtl.sh
  examples/tedlium/s5_r2/run.sh
  examples/tedlium/s5_r2/run_2mtl.sh
  utils/make_vocab.sh
  utils/map2phone.py
Labels: refactoring

#197 Random state passing
  examples/tedlium/s5_r2/conf/asr/mocha/lstm_mocha_rsp_enc.yaml
  neural_sp/models/seq2seq/encoders/build.py
  neural_sp/models/seq2seq/encoders/rnn.py
  test/encoders/test_rnn_encoder.py
  test/encoders/test_rnn_encoder_streaming_chunkwise.py
Labels: new feature

#198 Fix CNN lookahead for streaming inference
  neural_sp/models/seq2seq/encoders/conv.py
  neural_sp/models/seq2seq/frontends/streaming.py
  test/encoders/test_rnn_encoder_streaming_chunkwise.py
Labels: bug, streaming

#199 Fix streaming recipe
  examples/csj/s5/local/score_streaming.sh
  examples/csj/s5/run_streaming.sh
  examples/tedlium/s5_r2/local/score_streaming.sh
  examples/tedlium/s5_r2/run_streaming.sh
  neural_sp/models/seq2seq/encoders/conv.py
  neural_sp/models/seq2seq/frontends/streaming.py
  test/encoders/test_rnn_encoder_streaming_chunkwise.py
Labels: bug, recipe, streaming

#200 Update CSJ configuration files
  examples/csj/s5/conf/asr/mocha/blstm_mocha.yaml
  examples/csj/s5/conf/asr/mocha/lcblstm_mocha_chunk4040.yaml
  examples/csj/s5/conf/asr/mocha/lcblstm_mocha_chunk4040_ctc_sync.yaml
  examples/csj/s5/conf/asr/mocha/lcblstm_mocha_chunk4040_decot16.yaml
  examples/csj/s5/conf/asr/mocha/lcblstm_mocha_chunk4040_minlt.yaml
  examples/csj/s5/conf/asr/mocha/lstm_mocha.yaml
  examples/csj/s5/conf/asr/mocha/lstm_mocha_ctc_sync.yaml
  examples/csj/s5/conf/data/pretrain.yaml
  examples/csj/s5/conf/data/spec_augment_pretrain_F13_T50.yaml
  examples/csj/s5/conf/data/spec_augment_pretrain_F27_T100.yaml
  examples/csj/s5/conf/data/spec_augment_pretrain_F27_T50.yaml
  examples/csj/s5/conf/data/spec_augment_speed_perturb_transformer_subsample8.yaml
  examples/csj/s5/conf/data/spec_augment_speed_perturb_transformer_subsample8_F27_T50.yaml
  examples/csj/s5/conf/lm/transformer_xl.yaml
  examples/csj/s5/conf/lm/transformerlm.yaml
Labels: recipe

#202 Update rnn.py
  neural_sp/models/seq2seq/encoders/rnn.py
Labels: bug

#204 Fix RNN-T beam search and shallow fusion
  neural_sp/models/seq2seq/decoders/beam_search.py
  neural_sp/models/seq2seq/decoders/rnn_transducer.py
  test/decoders/test_rnn_transducer_decoder.py
Labels: bug

#205 Update TEDLIUM2 configuration files
  README.md
  examples/tedlium/s5_r2/conf/asr/lstm_mocha_ctc_sync.yaml
  examples/tedlium/s5_r2/conf/asr/mocha/lcblstm_mocha_chunk4040_mbr.yaml
  examples/tedlium/s5_r2/conf/asr/mocha/lstm_mocha_minlt.yaml
  examples/tedlium/s5_r2/conf/asr/transducer/blstm_rnnt_bpe1000.yaml
  examples/tedlium/s5_r2/conf/asr/transducer/lcblstm_rnnt_40_40_bpe1000.yaml
  examples/tedlium/s5_r2/conf/asr/transducer/lstm_rnnt_bpe1000.yaml
Labels: recipe

#206 Add test for streaming decoding on MoChA
  test/decoders/test_las_decoder.py
Labels: streaming, test

#207 Add tests for frontends
  neural_sp/models/seq2seq/frontends/frame_stacking.py
  neural_sp/models/seq2seq/frontends/spec_augment.py
  neural_sp/models/seq2seq/frontends/splicing.py
  test/frontends/test_frame_stacking.py
  test/frontends/test_specaugment.py
  test/frontends/test_splicing.py
Labels: test

#208 Fix bug in MTL + hierarchical subsampling
  neural_sp/models/seq2seq/encoders/encoder_base.py
  neural_sp/models/seq2seq/encoders/rnn.py
  test/encoders/test_rnn_encoder.py
Labels: bug

#209 Cache token embeddings during streaming inference
  neural_sp/models/lm/gated_convlm.py
  neural_sp/models/lm/lm_base.py
  neural_sp/models/lm/rnnlm.py
  neural_sp/models/lm/transformer_xl.py
  neural_sp/models/lm/transformerlm.py
  neural_sp/models/seq2seq/decoders/beam_search.py
  neural_sp/models/seq2seq/decoders/las.py
  test/decoders/test_las_decoder.py
Labels: streaming

#211 Refactor hypothesis initialization in LAS
  neural_sp/models/seq2seq/decoders/las.py
  test/decoders/dict.txt
  test/decoders/test_las_decoder.py
Labels: refactoring

#213 CTC visualization for the sub task
  neural_sp/bin/asr/plot_attention.py
  neural_sp/bin/plot_utils.py
Labels: new feature

#214 Fix bug in evaluation
  examples/ci_test/local/score.sh
  neural_sp/bin/asr/eval.py
  test/test_training.sh
Labels: bug

#216 Fix bug in loss calculation in pytorch==1.6.0
  neural_sp/models/criterion.py
Labels: bug

#215 Fix a bug while loading external LM through 'load_checkpoint' function.
  neural_sp/models/seq2seq/speech2text.py
Labels: bug

#217 Fix block-synchronous decoding for MoChA
  neural_sp/models/seq2seq/decoders/las.py
  neural_sp/models/seq2seq/frontends/streaming.py
  neural_sp/models/seq2seq/speech2text.py
  test/decoders/test_las_decoder.py
Labels: bug, streaming

#219 Add check for incremental input
  neural_sp/models/modules/causal_conv.py
  neural_sp/models/modules/conformer_convolution.py
  test/modules/test_causal_conv.py
  test/modules/test_conformer_convolution.py
Labels: test

#220 Refactor GMM attention
  neural_sp/models/modules/gmm_attention.py
  neural_sp/models/modules/softplus.py
  test/modules/test_gmm_attention.py
Labels: refactoring

#221 Add AMI recipe
  examples/ami/README.txt
  examples/ami/s5b/README.txt
  examples/ami/s5b/cmd.sh
  examples/ami/s5b/conf/ami_beamformit.cfg
  examples/ami/s5b/conf/asr/blstm_las.yaml
  examples/ami/s5b/conf/asr/blstm_mocha.yaml
  examples/ami/s5b/conf/asr/blstm_rnnt.yaml
  examples/ami/s5b/conf/asr/lcblstm_mocha_chunk4040.yaml
  examples/ami/s5b/conf/asr/lcblstm_mocha_chunk4040_ctc_sync.yaml
  examples/ami/s5b/conf/asr/lcblstm_rnnt_40_40.yaml
  examples/ami/s5b/conf/asr/transformer.yaml
  examples/ami/s5b/conf/data/pretrain.yaml
  examples/ami/s5b/conf/data/spec_augment.yaml
  examples/ami/s5b/conf/data/spec_augment_speed_perturb.yaml
  examples/ami/s5b/conf/data/spec_augment_speed_perturb_pretrain_F27_T100.yaml
  examples/ami/s5b/conf/data/spec_augment_speed_perturb_pretrain_F27_T50.yaml
  examples/ami/s5b/conf/data/spec_augment_speed_perturb_transformer.yaml
  examples/ami/s5b/conf/data/speed_perturb.yaml
  examples/ami/s5b/conf/data/speed_perturb_transformer.yaml
  examples/ami/s5b/conf/fbank.conf
  examples/ami/s5b/conf/lm/rnnlm.yaml
  examples/ami/s5b/local/ami_beamform.sh
  examples/ami/s5b/local/ami_download.sh
  examples/ami/s5b/local/ami_format_data.sh
  examples/ami/s5b/local/ami_ihm_data_prep.sh
  examples/ami/s5b/local/ami_ihm_scoring_data_prep.sh
  examples/ami/s5b/local/ami_mdm_data_prep.sh
  examples/ami/s5b/local/ami_mdm_scoring_data_prep.sh
  examples/ami/s5b/local/ami_prepare_dict.sh
  examples/ami/s5b/local/ami_sdm_data_prep.sh
  examples/ami/s5b/local/ami_sdm_scoring_data_prep.sh
  examples/ami/s5b/local/ami_split_segments.pl
  examples/ami/s5b/local/ami_text_prep.sh
  examples/ami/s5b/local/ami_xml2text.sh
  examples/ami/s5b/local/beamformit.sh
  examples/ami/s5b/local/convert2stm.pl
  examples/ami/s5b/local/english.glm
  examples/ami/s5b/local/score.sh
  examples/ami/s5b/local/split_REAMDE.txt
  examples/ami/s5b/local/split_dev.orig
  examples/ami/s5b/local/split_eval.orig
  examples/ami/s5b/local/split_train.orig
  examples/ami/s5b/path.sh
  examples/ami/s5b/run.sh
  examples/ami/s5b/steps
  examples/ami/s5b/utils
Labels: recipe

#222 Oracle WER calculation
  examples/aishell/s5/local/score.sh
  examples/ci_test/local/score.sh
  examples/ci_test/run.sh
  examples/ci_test/run_2mtl.sh
  examples/csj/s5/local/score.sh
  examples/csj/s5/local/score_streaming.sh
  examples/librispeech/s5/local/score.sh
  examples/swbd/s5c/local/score.sh
  examples/tedlium/s5_r2/local/score.sh
  examples/tedlium/s5_r2/local/score_streaming.sh
  examples/tedlium/s5_r3/local/score.sh
  examples/wsj/s5/local/score.sh
  neural_sp/bin/args_asr.py
  neural_sp/bin/args_lm.py
  neural_sp/bin/asr/eval.py
  neural_sp/bin/lm/train.py
  neural_sp/bin/train_utils.py
  neural_sp/evaluators/accuracy.py
  neural_sp/evaluators/character.py
  neural_sp/evaluators/phone.py
  neural_sp/evaluators/ppl.py
  neural_sp/evaluators/word.py
  neural_sp/evaluators/wordpiece.py
  neural_sp/evaluators/wordpiece_bleu.py
  neural_sp/models/seq2seq/decoders/ctc.py
  neural_sp/models/seq2seq/decoders/decoder_base.py
  neural_sp/models/seq2seq/speech2text.py
  neural_sp/trainers/lr_scheduler.py
  test/decoders/test_las_decoder.py
  test/test_training.sh
Labels: bug, new feature, test

#224 Fix bug in block-synchronous decoding
  README.md
  examples/ci_test/run.sh
  examples/ci_test/run_2mtl.sh
  neural_sp/models/seq2seq/decoders/las.py
  neural_sp/models/seq2seq/speech2text.py
  setup.cfg
  test/test_training.sh
Labels: bug, streaming

#225 Path merging in RNN-T beam search
  README.md
  neural_sp/models/lm/gated_convlm.py
  neural_sp/models/lm/rnnlm.py
  neural_sp/models/lm/transformer_xl.py
  neural_sp/models/lm/transformerlm.py
  neural_sp/models/seq2seq/decoders/beam_search.py
  neural_sp/models/seq2seq/decoders/rnn_transducer.py
Labels: enhancement

#230 Refactor streaming decoding in MoChA
  neural_sp/models/modules/attention.py
  neural_sp/models/modules/cif.py
  neural_sp/models/modules/gmm_attention.py
  neural_sp/models/modules/mocha.py
  neural_sp/models/modules/multihead_attention.py
  neural_sp/models/seq2seq/decoders/las.py
  test/modules/test_mocha.py
Labels: bug, refactoring, streaming

#231 Fix bug in attention/CTC plotting
  examples/ci_test/plot_attention.sh
  examples/ci_test/plot_ctc.sh
  examples/ci_test/score.sh
  neural_sp/bin/asr/plot_attention.py
  neural_sp/bin/asr/plot_ctc.py
  test/test_training.sh
Labels: bug, test

#233 Fix bug in block-synchronous decoding for LC-BLSTM encoder
  neural_sp/models/seq2seq/frontends/streaming.py
  neural_sp/models/seq2seq/speech2text.py
Labels: bug, streaming

#234 Fix bug in beam search for GMM attention
  neural_sp/models/modules/attention.py
  neural_sp/models/modules/cif.py
  neural_sp/models/modules/gmm_attention.py
  neural_sp/models/modules/mocha.py
  neural_sp/models/modules/multihead_attention.py
  neural_sp/models/modules/transformer.py
  neural_sp/models/seq2seq/decoders/las.py
  test/modules/test_attention.py
  test/modules/test_cif.py
  test/modules/test_gmm_attention.py
  test/modules/test_mocha.py
  test/modules/test_multihead_attention.py
Labels: bug

#235 Fix bug in streaming decoding
  neural_sp/models/seq2seq/frontends/streaming.py
  neural_sp/models/seq2seq/speech2text.py
Labels: bug, streaming

#236 Modularize Transformer/Conformer encoder
  neural_sp/models/seq2seq/encoders/conformer.py
  neural_sp/models/seq2seq/encoders/conformer_block.py
  neural_sp/models/seq2seq/encoders/transformer.py
  neural_sp/models/seq2seq/encoders/transformer_block.py
Labels: bug, refactoring
