Repository hirofumi0810/neural_sp, pull requests merged in 2020-10, with the labels that each got.

#160 Add final layer normalization to Conformer encoder
  neural_sp/models/seq2seq/encoders/conformer.py
Labels: enhancement

#164 Fix tensorboard reporting
  neural_sp/trainers/reporter.py
Labels: bug

#166 Batch-level CTC-based forced alignment
  examples/librispeech/s5/local/ctc_forced_align.sh
  examples/tedlium/s5_r2/local/ctc_forced_align.sh
  neural_sp/bin/asr/ctc_forced_align.py
  neural_sp/datasets/asr.py
  neural_sp/datasets/utils.py
  neural_sp/models/seq2seq/decoders/ctc.py
  neural_sp/models/seq2seq/decoders/decoder_base.py
  neural_sp/models/seq2seq/speech2text.py
Labels: new feature

#167 Add trigger for quantity loss and scheduled sampling during training
  examples/aishell/s5/conf/asr/blstm_las.yaml
  examples/ci_test/conf/asr/blstm_ctc.yaml
  examples/ci_test/conf/asr/blstm_las.yaml
  examples/ci_test/conf/asr/blstm_las_2mtl.yaml
  examples/ci_test/conf/asr/blstm_las_2mtl_per_batch.yaml
  examples/ci_test/conf/asr/tds_las.yaml
  examples/ci_test/conf/asr/transformer_las.yaml
  examples/csj/s5/conf/asr/blstm_las.yaml
  examples/csj/s5/conf/asr/blstm_las_2mtl.yaml
  examples/csj/s5/conf/asr/lcblstm_las_chunk4040.yaml
  examples/csj/s5/conf/asr/lstm_las.yaml
  examples/librispeech/s5/conf/asr/blstm_las.yaml
  examples/swbd/s5c/conf/asr/blstm_las.yaml
  examples/swbd/s5c/conf/asr/blstm_las_2mtl.yaml
  examples/swbd/s5c/conf/asr/blstm_las_3mtl.yaml
  examples/swbd/s5c/conf/asr/blstm_las_fisher_swbd.yaml
  examples/tedlium/s5_r2/conf/asr/blstm_las.yaml
  examples/tedlium/s5_r2/conf/asr/blstm_las_ctc_sync.yaml
  examples/tedlium/s5_r2/conf/asr/lcblstm_las_chunk4020.yaml
  examples/tedlium/s5_r2/conf/asr/lcblstm_las_chunk4040.yaml
  examples/tedlium/s5_r2/conf/asr/lstm_las.yaml
  examples/tedlium/s5_r3/conf/asr/blstm_las.yaml
  examples/timit/s5/conf/blstm_las.yaml
  examples/wsj/s5/conf/asr/blstm_las.yaml
  neural_sp/bin/args_asr.py
  neural_sp/bin/asr/train.py
  neural_sp/bin/model_name.py
  neural_sp/models/seq2seq/decoders/build.py
  neural_sp/models/seq2seq/decoders/decoder_base.py
  neural_sp/models/seq2seq/decoders/las.py
  neural_sp/models/seq2seq/decoders/rnn_transducer.py
  neural_sp/models/seq2seq/speech2text.py
  test/decoders/test_las_decoder.py
Labels: new feature

#169 Update train.py
  neural_sp/bin/asr/train.py
Labels: bug

#170 Fix gradient accumulation for LM training
  neural_sp/bin/lm/train.py
Labels: bug

#171 Lookahead frame option for unidirectional Transformer/Conformer encoder
  neural_sp/models/seq2seq/encoders/build.py
  neural_sp/models/seq2seq/encoders/conformer.py
  neural_sp/models/seq2seq/encoders/rnn.py
  neural_sp/models/seq2seq/encoders/subsampling.py
  neural_sp/models/seq2seq/encoders/transformer.py
  test/encoders/test_conformer_encoder.py
  test/encoders/test_rnn_encoder.py
  test/encoders/test_rnn_encoder_streaming_chunkwise.py
  test/encoders/test_transformer_encoder.py
Labels: new feature

#176 I just upgrade numpy
  tools/Makefile
Labels: bug

#179 Fix alignment loading
  examples/tedlium/s5_r2/conf/asr/mocha/lstm_mocha_decot16.yaml
  examples/tedlium/s5_r2/conf/asr/mocha/lstm_mocha_minlt.yaml
  neural_sp/bin/args_asr.py
  neural_sp/bin/asr/train.py
  neural_sp/datasets/alignment.py
  neural_sp/datasets/asr.py
  neural_sp/datasets/token_converter/character.py
  neural_sp/datasets/token_converter/phone.py
  neural_sp/datasets/token_converter/word.py
  neural_sp/datasets/token_converter/wordpiece.py
  neural_sp/datasets/utils.py
Labels: bug
